services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
  varnish:
    image: varnish:latest
    ports:
      - "9090:80"
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    environment:
      - VARNISH_SIZE=64M
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    ports:
      - "9191:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
